data_transformation:

  root_dir: artifacts/data_transformation

  train_path: artifacts/data_transformation/train.csv

  test_path: artifacts/data_transformation/test.csv

model_trainer:

  root_dir: artifacts/model_trainer

  trained_model_path: artifacts/model_trainer/model.pkl